---
version: '3.7'
services:
    mysql:
        image: mysql:5.6
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'

    maxscale:
      build:
        context: .
        dockerfile: Dockerfile.maxscale
      environment:
        DB_USER: 'maxuser'
        DB_PASS: 'maxpwd'
      ports:
        - "3306:3306"  # proxy port
        - "8989:8989"  # REST API port

