---
version: '3.7'
services:
    mysql:
        image: mysql:5.6
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        ports:
            - "3306:3306"

    maxscale:
      build:
        context: .
        dockerfile: Dockerfile.maxscale
        #        depends_on:
        #            - mysql
        #        ports:
        #            - "4008:4008"  # proxy port
        #            - "8989:8989"  # REST API port
